[build]
    base = "/"
    publish = "packages/decomposerize-website/build"
    command = "make build"

[[headers]]
  for = "/*"
  [headers.values]
    # For clients still on the old cached version of the app...
    Access-Control-Allow-Origin = "https://decomposerize.com"

    # To bust the cache that the CRA service worker set...
	cache-control = '''
	max-age=0,
	no-cache,
	no-store,
	must-revalidate'''
